# Generated by Django 3.2.13 on 2022-12-14 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=100000000)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
